# Generated by Django 4.2.23 on 2025-09-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zastepstwa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='subjects',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='can_teach',
            field=models.ManyToManyField(blank=True, related_name='lecturers_can_teach', to='zastepstwa.subject'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
