# Generated by Django 4.2.23 on 2025-09-03 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zastepstwa', '0002_remove_lecturer_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='substitution',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='can_teach',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to='zastepstwa.qualification'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to='zastepstwa.subject'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='substitute_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_substitutions', to='zastepstwa.lecturer'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zastepstwa.lecturer'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zastepstwa.subject'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='first_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='last_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='max_hours_per_week',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='max_substitutions_per_week',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='subject',
            name='required_qualifications',
            field=models.ManyToManyField(blank=True, related_name='subjects_required_for', to='zastepstwa.qualification'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='substitution', to='zastepstwa.classsession'),
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='substitute',
        ),
    ]
