# Generated by Django 4.2.23 on 2025-09-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zastepstwa', '0003_alter_substitution_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='required_qualifications',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
