# Generated by Django 4.2.23 on 2025-09-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zastepstwa', '0004_remove_lecturer_qualifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LecturerUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zastepstwa.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to='zastepstwa.qualification'),
        ),
        migrations.AddField(
            model_name='subject',
            name='required_qualifications',
            field=models.ManyToManyField(blank=True, related_name='subjects_required_for', to='zastepstwa.qualification'),
        ),
    ]
